name: Build and Run Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check Docker version
        run: docker version

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t apache-image:latest .

      # Run the Docker container
      - name: Run Docker container
        run: docker run -d -p 8080:80 --name apache-container  apache-image:latest

      # Verify that the container is running
      - name: Verify container is running
        run: docker ps
        
      - name: Write script inside container and output
        run: |
          docker exec apache-container sh -c 'echo "#!/bin/bash" > /usr/local/bin/my-script.sh && echo "echo \"Hello, world!\"" >> /usr/local/bin/my-script.sh && chmod +x /usr/local/bin/my-script.sh' 
          docker exec apache-container cat /usr/local/bin/my-script.sh
  
