name: Build and Run Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Docker
      - name: Install Docker
        uses: docker/setup-docker@v2
        with:
          dockerfile: Dockerfile
          container-name: my-docker-container

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t apache-image:latest .

      # Run the Docker container
      - name: Run Docker container
        run: docker run -d -p 8080:80 apache-image:latest

      # Verify that the container is running
      - name: Verify container is running
        run: docker ps
